<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXdxxN6N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXdxxN6N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXdxxN6N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXdxxN6N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXdxxN6N\App_KernelDevDebugContainer([
    'container.build_hash' => 'XdxxN6N',
    'container.build_id' => '080a6108',
    'container.build_time' => 1713966509,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXdxxN6N');
