<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBfBLApq\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBfBLApq/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerBfBLApq.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerBfBLApq\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerBfBLApq\App_KernelProdContainer([
    'container.build_hash' => 'BfBLApq',
    'container.build_id' => 'e60cfd32',
    'container.build_time' => 1713967397,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBfBLApq');
