<?php declare(strict_types=1);
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in the Configuration section of the admin interface.

// Generated from 'domserver-static.php.in' on Sat Apr 27 09:18:16 UTC 2024.

define('DOMJUDGE_VERSION', '8.2.3');

define('BINDIR',      '/opt/domjudge/domserver/bin');
define('ETCDIR',      '/opt/domjudge/domserver/etc');
define('WEBAPPDIR',   '/opt/domjudge/domserver/webapp');
define('LIBDIR',      '/opt/domjudge/domserver/lib');
define('SQLDIR',      '/opt/domjudge/domserver/sql');
define('LIBVENDORDIR','/opt/domjudge/domserver/lib/vendor');
define('LOGDIR',      '/opt/domjudge/domserver/log');
define('RUNDIR',      '/opt/domjudge/domserver/run');
define('TMPDIR',      '/opt/domjudge/domserver/tmp');

define('BASEURL',     'https://example.com/domjudge/');
