<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BkDHJOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.BkDHJO_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.BkDHJO_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'problem' => ['privates', '.errored..service_locator.BkDHJO_.App\\Entity\\Problem', NULL, 'Cannot autowire service ".service_locator.BkDHJO_": it references class "App\\Entity\\Problem" but no such service exists.'],
        ], [
            'problem' => 'App\\Entity\\Problem',
        ]);
    }
}
