<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9DUN5ZNService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9DUN5ZN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9DUN5ZN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'submission' => ['privates', '.errored..service_locator.9DUN5ZN.App\\Entity\\Submission', NULL, 'Cannot autowire service ".service_locator.9DUN5ZN": it references class "App\\Entity\\Submission" but no such service exists.'],
        ], [
            'submission' => 'App\\Entity\\Submission',
        ]);
    }
}
