<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Sentry_Traceable_HttpClientService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.sentry.traceable.http_client' shared service.
     *
     * @return \Sentry\SentryBundle\Tracing\HttpClient\TraceableHttpClient
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/sentry/sentry-symfony/src/Tracing/HttpClient/AbstractTraceableHttpClient.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/sentry/sentry-symfony/src/Tracing/HttpClient/TraceableHttpClientForV6.php';

        return $container->privates['.sentry.traceable.http_client'] = new \Sentry\SentryBundle\Tracing\HttpClient\TraceableHttpClient(($container->privates['.debug.http_client'] ?? $container->get_Debug_HttpClientService()), ($container->privates['Sentry\\State\\HubInterface'] ?? $container->getHubInterfaceService()));
    }
}
