<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3drNImGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3drNImG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3drNImG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'violations' => ['privates', '.errored..service_locator.3drNImG.Symfony\\Component\\Validator\\ConstraintViolationListInterface', NULL, 'Cannot autowire service ".service_locator.3drNImG": it references interface "Symfony\\Component\\Validator\\ConstraintViolationListInterface" but no such service exists. Did you create a class that implements this interface?'],
        ], [
            'violations' => 'Symfony\\Component\\Validator\\ConstraintViolationListInterface',
        ]);
    }
}
