<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WUxE3MoService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.WUxE3Mo' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.WUxE3Mo'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'debugPackage' => ['privates', '.errored..service_locator.WUxE3Mo.App\\Entity\\DebugPackage', NULL, 'Cannot autowire service ".service_locator.WUxE3Mo": it references class "App\\Entity\\DebugPackage" but no such service exists.'],
        ], [
            'debugPackage' => 'App\\Entity\\DebugPackage',
        ]);
    }
}
