<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBalloonController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Jury\BalloonController' shared autowired service.
     *
     * @return \App\Controller\Jury\BalloonController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Jury/BalloonController.php';

        $container->services['App\\Controller\\Jury\\BalloonController'] = $instance = new \App\Controller\Jury\BalloonController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService()), ($container->services['App\\Service\\ConfigurationService'] ?? $container->getConfigurationServiceService()), ($container->privates['App\\Service\\EventLogService'] ?? $container->getEventLogServiceService()));

        $instance->setContainer(($container->privates['.service_locator.9hK1Zku'] ?? $container->load('get_ServiceLocator_9hK1ZkuService'))->withContext('App\\Controller\\Jury\\BalloonController', $container));

        return $instance;
    }
}
