<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCache_SystemClearerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'cache.system_clearer' shared service.
     *
     * @return \Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/http-kernel/CacheClearer/CacheClearerInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/http-kernel/CacheClearer/Psr6CacheClearer.php';

        return $container->services['cache.system_clearer'] = new \Symfony\Component\HttpKernel\CacheClearer\Psr6CacheClearer(['cache.system' => ($container->services['cache.system'] ?? $container->getCache_SystemService()), 'cache.validator' => ($container->privates['cache.validator.traceable'] ?? $container->getCache_Validator_TraceableService()), 'cache.serializer' => ($container->privates['cache.serializer.traceable'] ?? $container->getCache_Serializer_TraceableService()), 'cache.annotations' => ($container->privates['cache.annotations.traceable'] ?? $container->getCache_Annotations_TraceableService()), 'cache.property_info' => ($container->privates['cache.property_info.traceable'] ?? $container->getCache_PropertyInfo_TraceableService()), 'cache.validator_expression_language' => ($container->services['cache.validator_expression_language'] ?? $container->getCache_ValidatorExpressionLanguageService()), 'cache.security_expression_language' => ($container->privates['cache.security_expression_language.traceable'] ?? $container->getCache_SecurityExpressionLanguage_TraceableService())]);
    }
}
