<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDebugPackageService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.WUxE3Mo.App\Entity\DebugPackage' shared service.
     *
     * @return \App\Entity\DebugPackage
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.WUxE3Mo": it references class "App\\Entity\\DebugPackage" but no such service exists.');
    }
}
