<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJmsSerializer_TwigExtension_SerializerRuntimeHelperService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'jms_serializer.twig_extension.serializer_runtime_helper' shared service.
     *
     * @return \JMS\Serializer\Twig\SerializerRuntimeHelper
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/jms/serializer/src/Twig/SerializerRuntimeHelper.php';

        $a = ($container->services['jms_serializer'] ?? $container->load('getJmsSerializerService'));

        if (isset($container->privates['jms_serializer.twig_extension.serializer_runtime_helper'])) {
            return $container->privates['jms_serializer.twig_extension.serializer_runtime_helper'];
        }

        return $container->privates['jms_serializer.twig_extension.serializer_runtime_helper'] = new \JMS\Serializer\Twig\SerializerRuntimeHelper($a);
    }
}
