<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getJudgingRunService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.1htcX.C.App\Entity\JudgingRun' shared service.
     *
     * @return \App\Entity\JudgingRun
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.1htcX.C": it references class "App\\Entity\\JudgingRun" but no such service exists.');
    }
}
