<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMonolog_Logger_EventfeedimporterService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'monolog.logger.event-feed-importer' shared service.
     *
     * @return \Symfony\Bridge\Monolog\Logger
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['monolog.logger.event-feed-importer'] = $instance = new \Symfony\Bridge\Monolog\Logger('event-feed-importer');

        $instance->pushProcessor(($container->privates['debug.log_processor'] ?? $container->getDebug_LogProcessorService()));
        $instance->pushProcessor(($container->privates['App\\Logger\\VarargsLogMessageProcessor'] ?? ($container->privates['App\\Logger\\VarargsLogMessageProcessor'] = new \App\Logger\VarargsLogMessageProcessor())));
        $instance->pushHandler(($container->privates['monolog.handler.event_feed_importer'] ?? $container->load('getMonolog_Handler_EventFeedImporterService')));
        \Symfony\Bundle\FrameworkBundle\DependencyInjection\Compiler\AddDebugLogProcessorPass::configureLogger($instance);

        return $instance;
    }
}
