<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRootControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\RootController' shared autowired service.
     *
     * @return \App\Controller\RootController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/RootController.php';

        $container->services['App\\Controller\\RootController'] = $instance = new \App\Controller\RootController(($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService()));

        $instance->setContainer(($container->privates['.service_locator.9hK1Zku'] ?? $container->load('get_ServiceLocator_9hK1ZkuService'))->withContext('App\\Controller\\RootController', $container));

        return $instance;
    }
}
