<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRejudgingServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\RejudgingService' shared autowired service.
     *
     * @return \App\Service\RejudgingService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/RejudgingService.php';

        $a = ($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService());

        if (isset($container->privates['App\\Service\\RejudgingService'])) {
            return $container->privates['App\\Service\\RejudgingService'];
        }
        $b = ($container->privates['App\\Service\\ScoreboardService'] ?? $container->getScoreboardServiceService());

        if (isset($container->privates['App\\Service\\RejudgingService'])) {
            return $container->privates['App\\Service\\RejudgingService'];
        }
        $c = ($container->privates['App\\Service\\EventLogService'] ?? $container->getEventLogServiceService());

        if (isset($container->privates['App\\Service\\RejudgingService'])) {
            return $container->privates['App\\Service\\RejudgingService'];
        }

        return $container->privates['App\\Service\\RejudgingService'] = new \App\Service\RejudgingService(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), $a, $b, $c, ($container->privates['App\\Service\\BalloonService'] ?? $container->load('getBalloonServiceService')));
    }
}
