<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSetExternalIdVisitorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Serializer\SetExternalIdVisitor' shared autowired service.
     *
     * @return \App\Serializer\SetExternalIdVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/jms/serializer/src/EventDispatcher/EventSubscriberInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Serializer/SetExternalIdVisitor.php';

        return $container->privates['App\\Serializer\\SetExternalIdVisitor'] = new \App\Serializer\SetExternalIdVisitor(($container->privates['App\\Service\\EventLogService'] ?? $container->getEventLogServiceService()));
    }
}
