<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamVisitorService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Serializer\TeamVisitor' shared autowired service.
     *
     * @return \App\Serializer\TeamVisitor
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/jms/serializer/src/EventDispatcher/EventSubscriberInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Serializer/TeamVisitor.php';

        $a = ($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService());

        if (isset($container->privates['App\\Serializer\\TeamVisitor'])) {
            return $container->privates['App\\Serializer\\TeamVisitor'];
        }

        return $container->privates['App\\Serializer\\TeamVisitor'] = new \App\Serializer\TeamVisitor($a, ($container->privates['App\\Service\\EventLogService'] ?? $container->getEventLogServiceService()), ($container->services['request_stack'] ?? ($container->services['request_stack'] = new \Symfony\Component\HttpFoundation\RequestStack())));
    }
}
