<?php

namespace ContainerXdxxN6N;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUserController2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Jury\UserController' shared autowired service.
     *
     * @return \App\Controller\Jury\UserController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Jury/UserController.php';

        $container->services['App\\Controller\\Jury\\UserController'] = $instance = new \App\Controller\Jury\UserController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService()), ($container->services['App\\Service\\ConfigurationService'] ?? $container->getConfigurationServiceService()), ($container->services['kernel'] ?? $container->get('kernel', 1)), ($container->privates['App\\Service\\EventLogService'] ?? $container->getEventLogServiceService()), ($container->services['.container.private.security.token_storage'] ?? $container->get_Container_Private_Security_TokenStorageService()));

        $instance->setContainer(($container->privates['.service_locator.9hK1Zku'] ?? $container->load('get_ServiceLocator_9hK1ZkuService'))->withContext('App\\Controller\\Jury\\UserController', $container));

        return $instance;
    }
}
