<?php declare(strict_types=1);
// Do not edit this file!
// Use configure with the right parameters, and run 'make' and 'make install'
// Variables you can change are in the Configuration section of the admin interface.

// Generated from 'domserver-static.php.in' on Wed Apr 24 14:05:18 UTC 2024.

define('DOMJUDGE_VERSION', '8.2.3');

define('BINDIR',      '/home/usuario/domjudge-8.2.3/domserver/bin');
define('ETCDIR',      '/home/usuario/domjudge-8.2.3/domserver/etc');
define('WEBAPPDIR',   '/home/usuario/domjudge-8.2.3/domserver/webapp');
define('LIBDIR',      '/home/usuario/domjudge-8.2.3/domserver/lib');
define('SQLDIR',      '/home/usuario/domjudge-8.2.3/domserver/sql');
define('LIBVENDORDIR','/home/usuario/domjudge-8.2.3/domserver/lib/vendor');
define('LOGDIR',      '/home/usuario/domjudge-8.2.3/domserver/log');
define('RUNDIR',      '/home/usuario/domjudge-8.2.3/domserver/run');
define('TMPDIR',      '/home/usuario/domjudge-8.2.3/domserver/tmp');

define('BASEURL',     'https://example.com/domjudge/');
