<?php

namespace ContainerBfBLApq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AvS4jiService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator._avS4ji' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._avS4ji'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'balloonService' => ['privates', 'App\\Service\\BalloonService', 'getBalloonServiceService', true],
        ], [
            'balloonService' => 'App\\Service\\BalloonService',
        ]);
    }
}
