<?php

namespace ContainerBfBLApq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QL_U2I5Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.qL.u2I5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qL.u2I5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jid' => ['privates', '.errored..service_locator.qL.u2I5.App\\Entity\\Judging', NULL, 'Cannot autowire service ".service_locator.qL.u2I5": it references class "App\\Entity\\Judging" but no such service exists.'],
            'jrid' => ['privates', '.errored..service_locator.qL.u2I5.App\\Entity\\JudgingRun', NULL, 'Cannot autowire service ".service_locator.qL.u2I5": it references class "App\\Entity\\JudgingRun" but no such service exists.'],
        ], [
            'jid' => 'App\\Entity\\Judging',
            'jrid' => 'App\\Entity\\JudgingRun',
        ]);
    }
}
