<?php

namespace ContainerBfBLApq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Kh2RVIpService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Kh2RVIp' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Kh2RVIp'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'jid' => ['privates', '.errored..service_locator.Kh2RVIp.App\\Entity\\Judging', NULL, 'Cannot autowire service ".service_locator.Kh2RVIp": it references class "App\\Entity\\Judging" but no such service exists.'],
        ], [
            'jid' => 'App\\Entity\\Judging',
        ]);
    }
}
