<?php

namespace ContainerBfBLApq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ev3pD8sService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.Ev3pD8s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ev3pD8s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'projectDir' => ['privates', '.value.zrvvYJt', 'get_Value_ZrvvYJtService', true],
            'requestStack' => ['services', 'request_stack', 'getRequestStackService', false],
            'vendorDir' => ['privates', '.value.w53kaXi', 'get_Value_W53kaXiService', true],
        ], [
            'projectDir' => '?',
            'requestStack' => '?',
            'vendorDir' => '?',
        ]);
    }
}
