<?php

namespace ContainerBfBLApq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAwardServiceService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Service\AwardService' shared autowired service.
     *
     * @return \App\Service\AwardService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/AwardService.php';

        $a = ($container->privates['App\\Service\\EventLogService'] ?? $container->load('getEventLogServiceService'));

        if (isset($container->privates['App\\Service\\AwardService'])) {
            return $container->privates['App\\Service\\AwardService'];
        }

        return $container->privates['App\\Service\\AwardService'] = new \App\Service\AwardService($a);
    }
}
