<?php

namespace ContainerBfBLApq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateQuizControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\Jury\CreateQuizController' shared autowired service.
     *
     * @return \App\Controller\Jury\CreateQuizController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/BaseController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Jury/CreateQuizController.php';

        $container->services['App\\Controller\\Jury\\CreateQuizController'] = $instance = new \App\Controller\Jury\CreateQuizController();

        $instance->setContainer(($container->privates['.service_locator.MbiTQcK'] ?? $container->load('get_ServiceLocator_MbiTQcKService'))->withContext('App\\Controller\\Jury\\CreateQuizController', $container));

        return $instance;
    }
}
