<?php

namespace ContainerBfBLApq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProblemService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.BkDHJO_.App\Entity\Problem' shared service.
     *
     * @return \App\Entity\Problem
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.BkDHJO_": it references class "App\\Entity\\Problem" but no such service exists.');
    }
}
