<?php

namespace ContainerBfBLApq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamService extends App_KernelProdContainer
{
    /*
     * Gets the private '.errored..service_locator.p02vx.n.App\Entity\Team' shared service.
     *
     * @return \App\Entity\Team
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.p02vx.n": it references class "App\\Entity\\Team" but no such service exists.');
    }
}
