<?php

namespace ContainerBfBLApq;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTeamAffiliationTypeService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Form\Type\TeamAffiliationType' shared autowired service.
     *
     * @return \App\Form\Type\TeamAffiliationType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 5).'/lib/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/AbstractExternalIdEntityType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/TeamAffiliationType.php';

        $a = ($container->privates['App\\Service\\EventLogService'] ?? $container->load('getEventLogServiceService'));

        if (isset($container->privates['App\\Form\\Type\\TeamAffiliationType'])) {
            return $container->privates['App\\Form\\Type\\TeamAffiliationType'];
        }
        $b = ($container->privates['App\\Service\\DOMJudgeService'] ?? $container->getDOMJudgeServiceService());

        if (isset($container->privates['App\\Form\\Type\\TeamAffiliationType'])) {
            return $container->privates['App\\Form\\Type\\TeamAffiliationType'];
        }

        return $container->privates['App\\Form\\Type\\TeamAffiliationType'] = new \App\Form\Type\TeamAffiliationType($a, ($container->services['App\\Service\\ConfigurationService'] ?? $container->getConfigurationServiceService()), $b);
    }
}
